### ISSUE TITLE
Помогите запустить я помойму немного тупой)

### ISSUE THREAD

**Issue by 2Milan** [EXG1O/Constructor-Telegram-Bots#115]
![изображение](https://github.com/EXG1O/Constructor-Telegram-Bots/assets/97323306/c76794e6-732d-4b29-b485-2d5ead7dad11)
![изображение](https://github.com/EXG1O/Constructor-Telegram-Bots/assets/97323306/243d829d-3f10-4e6c-99d4-a8074e00ec5f)
![изображение](https://github.com/EXG1O/Constructor-Telegram-Bots/assets/97323306/109e21d7-9746-430f-a65c-3f7b064b759a)
![изображение](https://github.com/EXG1O/Constructor-Telegram-Bots/assets/97323306/70781b1c-c669-4bbe-86c6-ca5ac9534c5d)

На фото все настройки 
Базы поднял через докер проверил всё работает
Проблема в том что не приходят сообщения от бота для авторизации

**Comment by EXG1O** [comment]
Здравствуйте, вы Celery запустили?

**Comment by EXG1O** [comment]
Я  закрываю issue, потому-что прошло уже ~2 недели и никакого ответа.
