### ISSUE TITLE
Reverse Proxy 

### ISSUE THREAD

**Issue by AFedorovEC** [EXG1O/Constructor-Telegram-Bots#117]
Привет! Размещаюсь на VDS, никак не могу донастроить nginx. Постоянно пишет, что ip не разрешен. Как победить?

**Comment by EXG1O** [comment]
> Привет! Размещаюсь на VDS, никак не могу донастроить nginx. Постоянно пишет, что ip не разрешен. Как победить?
> 
> 

Здравствуйте, прочитайте пожалуйста лицензию проекта. Мне кажется, что вы её нарушаете.
